name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup/toolchains
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust and wasm32 target
        run: |
          rustup toolchain install stable
          rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo build --verbose

      - name: Build wasm32
        run: cargo build --target wasm32-unknown-unknown --verbose

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Tests
        run: cargo test --verbose

      - name: Fmt
        run: cargo fmt -- --check
